In [35]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
df=pd.read_csv(r"C:\Users\cse\Desktop\AI\coinmarketcap_06122017.csv")

In [37]:
df

Unnamed: 0  24h_volume_usd  available_supply                 id  \
0              0    9.007640e+09      1.672352e+07            bitcoin   
1              1    1.551330e+09      9.616537e+07           ethereum   
2              2    1.111350e+09      1.684044e+07       bitcoin-cash   
3              3    2.936090e+09      2.779530e+09               iota   
4              4    2.315050e+08      3.873915e+10             ripple   
5              5    2.289430e+08      7.736420e+06               dash   
6              6    4.093420e+08      5.415391e+07           litecoin   
7              7    1.384070e+08      1.669097e+07       bitcoin-gold   
8              8    5.498600e+08      1.544296e+07             monero   
9              9    6.164750e+07      2.592707e+10            cardano   
10            10    4.020670e+08      9.812566e+07   ethereum-classic   
11            11    3.172850e+07      9.000000e+09                nem   
12            12    2.490480e+08      5.199591e+08                eos   
13            13    1.133520e+08      6.500000e+07                neo   
14            14    2.578380e+08      1.783388e+10            stellar   
15            15    1.257440e+08      5.581722e+07           monacoin   
16            16    2.459810e+07      3.185692e+06         bitconnect   
17            17    6.965980e+07      1.156410e+08               lisk   
18            18    1.896010e+08      2.774181e+06              zcash   
19            19    6.003860e+07      1.020426e+08            omisego   
20            20    1.421220e+08      7.369633e+07               qtum   
21            21    1.084790e+09      8.140173e+08             tether   
22            22    4.676660e+07      1.000000e+08              waves   
23            23    3.733400e+07      9.864974e+07            stratis   
24            24    1.567790e+06      4.125225e+07           populous   
25            25    7.814140e+07      4.233708e+07             hshare   
26            26    9.387460e+06      9.989995e+08              ardor   
27            27    1.733630e+07      2.603860e+09          bitshares   
28            28    6.102460e+06      1.832535e+11       bytecoin-bcn   
29            29    2.077010e+07      9.798128e+07                ark   
...          ...             ...               ...                ...   
1296        1296    1.020000e+00               NaN           wowecoin   
1297        1297    3.753680e-01               NaN             bitfid   
1298        1298             NaN               NaN          vegascoin   
1299        1299             NaN               NaN     gameleaguecoin   
1300        1300             NaN               NaN         bitcentavo   
1301        1301             NaN               NaN          cybercoin   
1302        1302             NaN               NaN            eggcoin   
1303        1303             NaN               NaN          shellcoin   
1304        1304             NaN               NaN       deltacredits   
1305        1305             NaN               NaN             cashme   
1306        1306             NaN               NaN                 x2   
1307        1307             NaN               NaN           opescoin   
1308        1308             NaN               NaN       bitalphacoin   
1309        1309             NaN               NaN         psilocybin   
1310        1310             NaN               NaN               ocow   
1311        1311             NaN               NaN           safecoin   
1312        1312             NaN               NaN           pokecoin   
1313        1313             NaN               NaN         sportscoin   
1314        1314             NaN               NaN            omicron   
1315        1315             NaN               NaN            pinkdog   
1316        1316             NaN               NaN           teracoin   
1317        1317             NaN               NaN            zsecoin   
1318        1318             NaN               NaN              

In [39]:
df.head()

Unnamed: 0  24h_volume_usd  available_supply            id  last_updated  \
0           0    9.007640e+09      1.672352e+07       bitcoin    1512549554   
1           1    1.551330e+09      9.616537e+07      ethereum    1512549553   
2           2    1.111350e+09      1.684044e+07  bitcoin-cash    1512549578   
3           3    2.936090e+09      2.779530e+09          iota    1512549571   
4           4    2.315050e+08      3.873915e+10        ripple    1512549541   

   market_cap_usd    max_supply          name  percent_change_1h  \
0    2.130493e+11  2.100000e+07       Bitcoin               0.12   
1    4.352945e+10           NaN      Ethereum              -0.18   
2    2.529585e+10  2.100000e+07  Bitcoin Cash               1.65   
3    1.475225e+10  2.779530e+09          IOTA              -2.38   
4    9.365343e+09  1.000000e+11        Ripple               0.56   

   percent_change_24h  percent_change_7d  price_btc     price_usd  rank  \
0                7.33              17.45   1.000000  12739.500000     1   
1               -3.93              -7.33   0.036177    452.652000     2   
2               -5.51              -4.75   0.120050   1502.090000     3   
3               83.35             255.82   0.000424      5.307460     4   
4               -3.70             -14.79   0.000019      0.241754     5   

  symbol  total_supply  
0    BTC  1.672352e+07  
1    ETH  9.616537e+07  
2    BCH  1.684044e+07  
3  MIOTA  2.779530e+09  
4    XRP  9.999309e+10

In [40]:
df.isnull().any()

Unnamed: 0            False
24h_volume_usd         True
available_supply       True
id                    False
last_updated          False
market_cap_usd         True
max_supply             True
name                  False
percent_change_1h      True
percent_change_24h     True
percent_change_7d      True
price_btc             False
price_usd             False
rank                  False
symbol                False
total_supply           True
dtype: bool

In [41]:
df.drop(["id","symbol","rank","24h_volume_usd","available_supply","last_updated","market_cap_usd","max_supply","price_btc","price_usd"],axis=1,inplace=True)

In [42]:
df

Unnamed: 0               name  percent_change_1h  percent_change_24h  \
0              0            Bitcoin               0.12                7.33   
1              1           Ethereum              -0.18               -3.93   
2              2       Bitcoin Cash               1.65               -5.51   
3              3               IOTA              -2.38               83.35   
4              4             Ripple               0.56               -3.70   
5              5               Dash               1.22               -3.31   
6              6           Litecoin              -0.17                0.80   
7              7       Bitcoin Gold              -0.86               -8.65   
8              8             Monero              -2.00               25.65   
9              9            Cardano              -0.28               -5.80   
10            10   Ethereum Classic              -0.20               -3.47   
11            11                NEM              -0.70               -0.39   
12            12                EOS               2.26               29.56   
13            13                NEO               1.24               -7.28   
14            14     Stellar Lumens              -2.71               39.48   
15            15           MonaCoin              17.10              109.98   
16            16         BitConnect               0.49                3.70   
17            17               Lisk               1.06               -2.52   
18            18              Zcash              -0.99                9.00   
19            19            OmiseGO              -0.72               -8.06   
20            20               Qtum               0.36               -9.85   
21            21             Tether               0.17               -0.07   
22            22              Waves               0.97               -4.33   
23            23            Stratis               1.48               -6.64   
24            24           Populous              -0.39               16.05   
25            25             Hshare               0.24               -9.33   
26            26              Ardor               1.28               -6.55   
27            27          BitShares               4.99                9.20   
28            28           Bytecoin              -2.43                0.39   
29            29                Ark               0.29               -2.28   
...          ...                ...                ...                 ...   
1296        1296           Wowecoin                NaN                0.00   
1297        1297             BITFID               0.54                 NaN   
1298        1298          VegasCoin                NaN                 NaN   
1299        1299     GameLeagueCoin                NaN                 NaN   
1300        1300         BitCentavo                NaN                 NaN   
1301        1301          CyberCoin                NaN               -0.03   
1302        1302            EggCoin                NaN                 NaN   
1303        1303          ShellCoin                NaN                0.73   
1304        1304       DeltaCredits                NaN                 NaN   
1305        1305             Cashme                NaN                0.77   
1306        1306                 X2               0.21                5.94   
1307        1307           Opescoin                NaN               -0.42   
1308        1308       BitAlphaCoin                NaN                0.07   
1309        1309         Psilocybin                NaN               -0.72   
1310        1310               OCOW                NaN                 NaN   
1311        1311           SafeCoin                NaN               -1.12   
1312        1312           PokeCoin                NaN               -0.43   
1313        1313         SportsCoin                NaN                 NaN   
1314        1314            Omicron                NaN                0.89   
1315        1315            

In [43]:
df.isnull().any()

Unnamed: 0            False
name                  False
percent_change_1h      True
percent_change_24h     True
percent_change_7d      True
total_supply           True
dtype: bool

In [44]:
df.fillna(df.mean(),inplace=True)

In [45]:
df.isnull().any()

Unnamed: 0            False
name                  False
percent_change_1h     False
percent_change_24h    False
percent_change_7d     False
total_supply          False
dtype: bool

In [46]:
df

Unnamed: 0               name  percent_change_1h  percent_change_24h  \
0              0            Bitcoin           0.120000            7.330000   
1              1           Ethereum          -0.180000           -3.930000   
2              2       Bitcoin Cash           1.650000           -5.510000   
3              3               IOTA          -2.380000           83.350000   
4              4             Ripple           0.560000           -3.700000   
5              5               Dash           1.220000           -3.310000   
6              6           Litecoin          -0.170000            0.800000   
7              7       Bitcoin Gold          -0.860000           -8.650000   
8              8             Monero          -2.000000           25.650000   
9              9            Cardano          -0.280000           -5.800000   
10            10   Ethereum Classic          -0.200000           -3.470000   
11            11                NEM          -0.700000           -0.390000   
12            12                EOS           2.260000           29.560000   
13            13                NEO           1.240000           -7.280000   
14            14     Stellar Lumens          -2.710000           39.480000   
15            15           MonaCoin          17.100000          109.980000   
16            16         BitConnect           0.490000            3.700000   
17            17               Lisk           1.060000           -2.520000   
18            18              Zcash          -0.990000            9.000000   
19            19            OmiseGO          -0.720000           -8.060000   
20            20               Qtum           0.360000           -9.850000   
21            21             Tether           0.170000           -0.070000   
22            22              Waves           0.970000           -4.330000   
23            23            Stratis           1.480000           -6.640000   
24            24           Populous          -0.390000           16.050000   
25            25             Hshare           0.240000           -9.330000   
26            26              Ardor           1.280000           -6.550000   
27            27          BitShares           4.990000            9.200000   
28            28           Bytecoin          -2.430000            0.390000   
29            29                Ark           0.290000           -2.280000   
...          ...                ...                ...                 ...   
1296        1296           Wowecoin           1.052435            0.000000   
1297        1297             BITFID           0.540000            8.655677   
1298        1298          VegasCoin           1.052435            8.655677   
1299        1299     GameLeagueCoin           1.052435            8.655677   
1300        1300         BitCentavo           1.052435            8.655677   
1301        1301          CyberCoin           1.052435           -0.030000   
1302        1302            EggCoin           1.052435            8.655677   
1303        1303          ShellCoin           1.052435            0.730000   
1304        1304       DeltaCredits           1.052435            8.655677   
1305        1305             Cashme           1.052435            0.770000   
1306        1306                 X2           0.210000            5.940000   
1307        1307           Opescoin           1.052435           -0.420000   
1308        1308       BitAlphaCoin           1.052435            0.070000   
1309        1309         Psilocybin           1.052435           -0.720000   
1310        1310               OCOW           1.052435            8.655677   
1311        1311           SafeCoin           1.052435           -1.120000   
1312        1312           PokeCoin           1.052435           -0.430000   
1313        1313         SportsCoin           1.052435            8.655677   
1314        1314            Omicron           1.052435            0.890000   
1315        1315            

In [49]:
df.head()

Unnamed: 0          name  percent_change_1h  percent_change_24h  \
0           0       Bitcoin               0.12                7.33   
1           1      Ethereum              -0.18               -3.93   
2           2  Bitcoin Cash               1.65               -5.51   
3           3          IOTA              -2.38               83.35   
4           4        Ripple               0.56               -3.70   

   percent_change_7d  total_supply  
0              17.45  1.672352e+07  
1              -7.33  9.616537e+07  
2              -4.75  1.684044e+07  
3             255.82  2.779530e+09  
4             -14.79  9.999309e+10

In [47]:
x=df.iloc[:,2:5].values

In [48]:
x

array([[  0.12      ,   7.33      ,  17.45      ],
       [ -0.18      ,  -3.93      ,  -7.33      ],
       [  1.65      ,  -5.51      ,  -4.75      ],
       ...,
       [ -0.37      , -37.39      , -27.69      ],
       [  1.05243519,   4.39      , -22.84      ],
       [  1.05243519,   8.65567717,  -6.83      ]])

In [13]:
y=df.iloc[:,5].values

In [14]:
y

array([1.6723525e+07, 9.6165368e+07, 1.6840438e+07, ..., 2.5023800e+06,
       1.0200000e+10, 1.0000000e+07])

In [15]:
x

array([[  0.12      ,   7.33      ,  17.45      ],
       [ -0.18      ,  -3.93      ,  -7.33      ],
       [  1.65      ,  -5.51      ,  -4.75      ],
       ...,
       [ -0.37      , -37.39      , -27.69      ],
       [  1.05243519,   4.39      , -22.84      ],
       [  1.05243519,   8.65567717,  -6.83      ]])

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [17]:
x_train

array([[  0.54,   6.31,  15.17],
       [  0.54,   2.57,  11.09],
       [  0.52, -12.36, -22.62],
       ...,
       [-37.55, -63.75, -52.59],
       [  0.46,   0.78,  29.91],
       [ -1.53,   0.28,   1.48]])

In [18]:
y_train

array([7.8496447e+11, 7.8496447e+11, 5.3033136e+08, ..., 7.8496447e+11,
       3.5347000e+04, 7.9570760e+08])

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
mlr=LinearRegression()

In [21]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [22]:
y_pred=mlr.predict(x_test)

In [23]:
x_test

array([[ 1.25000000e+00,  4.70000000e+00, -1.63000000e+01],
       [ 5.40000000e-01,  6.31000000e+00,  1.70700000e+01],
       [ 1.71200000e+01,  2.50000000e-01,  9.39200000e+01],
       [ 1.72000000e+00, -1.61400000e+01,  3.41700000e+01],
       [ 5.10000000e-01,  4.36100000e+01,  1.12200000e+01],
       [-5.70000000e-01,  1.15200000e+01,  2.10900000e+01],
       [ 1.30000000e+00, -8.19000000e+00, -2.45000000e+00],
       [ 5.40000000e-01,  8.65567717e+00,  1.11390000e+02],
       [ 7.00000000e-01,  5.47000000e+00,  3.58100000e+01],
       [ 3.24000000e+00, -4.75700000e+01, -7.17000000e+01],
       [ 5.40000000e-01,  6.31000000e+00,  1.86700000e+01],
       [ 3.70000000e+00,  3.52000000e+00, -1.86100000e+01],
       [ 1.22300000e+01,  7.84000000e+00, -5.50000000e+00],
       [ 4.90000000e+00, -1.31600000e+01,  9.10000000e-01],
       [ 3.10000000e-01,  5.34000000e+00, -1.05000000e+01],
       [ 8.61000000e+00,  7.85800000e+01,  1.85760000e+02],
       [ 5.10000000e-01, -1.80000000e-01

In [24]:
y_test

array([1.62963900e+06, 2.45324000e+06, 7.84964470e+11, 1.84194753e+08,
       7.84964470e+11, 1.62940620e+07, 2.05218256e+08, 7.84964470e+11,
       1.34813000e+07, 9.84620900e+06, 7.84964470e+11, 3.00000000e+09,
       3.35655612e+10, 1.00000000e+10, 1.00000000e+08, 2.14748365e+09,
       6.00000000e+08, 8.03519300e+06, 4.42204000e+07, 6.04491100e+06,
       1.14780564e+08, 7.73642000e+06, 8.89996870e+07, 4.00000000e+08,
       1.00000000e+08, 1.00000000e+11, 2.96216000e+05, 1.96150190e+07,
       7.00112590e+07, 1.70622047e+08, 4.18392000e+07, 1.30271020e+08,
       5.29352682e+08, 8.33370000e+07, 7.84964470e+11, 1.99089100e+06,
       7.84964470e+11, 2.12680920e+07, 8.62186852e+08, 2.70000000e+07,
       1.69598616e+08, 5.00000000e+08, 2.31925310e+07, 7.84964470e+11,
       1.20731000e+06, 1.00000000e+09, 5.94105100e+08, 4.20658300e+06,
       2.48536697e+08, 1.21351980e+07, 9.74155440e+07, 2.49194000e+07,
       2.08039284e+10, 5.06293000e+07, 7.50231497e+08, 3.20903290e+12,
      

In [25]:
y_pred

array([7.82711192e+10, 7.69491551e+10, 7.20498177e+10, 7.23361779e+10,
       8.35085989e+10, 7.76460652e+10, 7.54363159e+10, 7.28182698e+10,
       7.59067206e+10, 7.21081513e+10, 7.68723830e+10, 7.81549900e+10,
       7.81543867e+10, 7.43968797e+10, 7.81114232e+10, 8.09262086e+10,
       7.80916416e+10, 7.79643113e+10, 7.48125307e+10, 7.73778146e+10,
       7.77095057e+10, 7.56305599e+10, 7.44330157e+10, 7.66464990e+10,
       7.66479331e+10, 7.59465798e+10, 7.51866826e+10, 7.55412682e+10,
       7.32380782e+10, 7.37738914e+10, 7.21787094e+10, 7.52599805e+10,
       7.53617399e+10, 7.31060323e+10, 7.70521998e+10, 7.67460386e+10,
       7.72272116e+10, 9.99515886e+10, 7.66733636e+10, 7.16444032e+10,
       5.50894135e+10, 7.75500952e+10, 7.69755143e+10, 7.73846132e+10,
       7.66583400e+10, 7.54397213e+10, 8.58752999e+10, 7.57886035e+10,
       7.52605859e+10, 7.39736140e+10, 7.46972731e+10, 7.99059668e+10,
       7.65647738e+10, 6.75945124e+10, 7.73238308e+10, 7.59989039e+10,
      

In [26]:
x_train.shape

(1060, 3)

In [27]:
pred=mlr.predict([[0.12,7.33,17.45]])

In [28]:
pred

array([7.71074697e+10])

In [30]:
y_pred=mlr.predict(x_test)

In [31]:
y_pred

array([7.82711192e+10, 7.69491551e+10, 7.20498177e+10, 7.23361779e+10,
       8.35085989e+10, 7.76460652e+10, 7.54363159e+10, 7.28182698e+10,
       7.59067206e+10, 7.21081513e+10, 7.68723830e+10, 7.81549900e+10,
       7.81543867e+10, 7.43968797e+10, 7.81114232e+10, 8.09262086e+10,
       7.80916416e+10, 7.79643113e+10, 7.48125307e+10, 7.73778146e+10,
       7.77095057e+10, 7.56305599e+10, 7.44330157e+10, 7.66464990e+10,
       7.66479331e+10, 7.59465798e+10, 7.51866826e+10, 7.55412682e+10,
       7.32380782e+10, 7.37738914e+10, 7.21787094e+10, 7.52599805e+10,
       7.53617399e+10, 7.31060323e+10, 7.70521998e+10, 7.67460386e+10,
       7.72272116e+10, 9.99515886e+10, 7.66733636e+10, 7.16444032e+10,
       5.50894135e+10, 7.75500952e+10, 7.69755143e+10, 7.73846132e+10,
       7.66583400e+10, 7.54397213e+10, 8.58752999e+10, 7.57886035e+10,
       7.52605859e+10, 7.39736140e+10, 7.46972731e+10, 7.99059668e+10,
       7.65647738e+10, 6.75945124e+10, 7.73238308e+10, 7.59989039e+10,
      

In [32]:
from sklearn.metrics import r2_score,accuracy_score

In [33]:
r2_score(y_test,y_pred)

-0.003911388118474912

In [34]:
df.corr()

Unnamed: 0  percent_change_1h  percent_change_24h  \
Unnamed: 0            1.000000           0.012846            0.011241   
percent_change_1h     0.012846           1.000000            0.201672   
percent_change_24h    0.011241           0.201672            1.000000   
percent_change_7d    -0.066647           0.082560            0.393188   
total_supply          0.012576          -0.001256           -0.001341   

                    percent_change_7d  total_supply  
Unnamed: 0                  -0.066647      0.012576  
percent_change_1h            0.082560     -0.001256  
percent_change_24h           0.393188     -0.001341  
percent_change_7d            1.000000     -0.002741  
total_supply                -0.002741      1.000000